# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'JJJ漫画初回限定版' do

pod ‘SSZipArchive’
pod ‘SDWebImage’
end

target 'JJJ漫画初回限定版Tests' do

pod ‘SSZipArchive’

end

target 'JJJ漫画初回限定版UITests' do

pod ‘SSZipArchive’

end

